#!/bin/bash
function separator() {
  echo "--------------------"
}

echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
read -p 'Answer: '  reply

if [[ $reply =~ ^[Yy]$ ]]
then
	sudo -v # ask password beforehand

	bash ~/.dotfiles/install
fi
