#!/bin/bash
function separator() {
  echo "--------------------"
}

echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
read -p 'Answer: '  reply

if [[ $reply =~ ^[Yy]$ ]]
then
	sudo -v #ask password beforehand
  read -n 1 -s -r -p "Are you logged into iCloud? Otherwise Mackup won't work. Press any key to continue."
	source ~/.dotfiles/install
fi
